// Code generated by protoc-gen-go.
// source: serverrpc.proto
// DO NOT EDIT!

/*
Package serversvc is a generated protocol buffer package.

It is generated from these files:
	serverrpc.proto

It has these top-level messages:
	ServerSvcStatusReq
	ServerSvcStatusReply
	SessionInfo
	ReviewInfo
	CCInfo
	BankInfo
	InstructorInfo
	Device
	UserInfo
	GetSessionsReq
	GetSessionsReply
	GetSessionReply
	GetSessionReq
	PostSessionReq
	PostSessionReply
	EnrollInstructorReq
	EnrollInstructorReply
	GetInstructorReq
	GetInstructorReply
	GetInstructorsReq
	GetInstructorsReply
	GetUserReq
	GetUserReply
	EnrollUserReq
	EnrollUserReply
	GetUsersReq
	GetUsersReply
	Event
	RecordActivity
	RecordEventReq
	RecordEventReply
	LoginReq
	LoginReply
*/
package serversvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FitnessCategory int32

const (
	FitnessCategory_YOGA           FitnessCategory = 0
	FitnessCategory_HATHA_YOGA     FitnessCategory = 1
	FitnessCategory_KUNDALINI_YOGA FitnessCategory = 2
	FitnessCategory_FAST_YOGA      FitnessCategory = 3
	FitnessCategory_MEDITATION     FitnessCategory = 101
	FitnessCategory_TM_MEDITATION  FitnessCategory = 102
	FitnessCategory_DANCE          FitnessCategory = 201
	FitnessCategory_HIP_HOP        FitnessCategory = 202
	FitnessCategory_ZUMBA          FitnessCategory = 203
)

var FitnessCategory_name = map[int32]string{
	0:   "YOGA",
	1:   "HATHA_YOGA",
	2:   "KUNDALINI_YOGA",
	3:   "FAST_YOGA",
	101: "MEDITATION",
	102: "TM_MEDITATION",
	201: "DANCE",
	202: "HIP_HOP",
	203: "ZUMBA",
}
var FitnessCategory_value = map[string]int32{
	"YOGA":           0,
	"HATHA_YOGA":     1,
	"KUNDALINI_YOGA": 2,
	"FAST_YOGA":      3,
	"MEDITATION":     101,
	"TM_MEDITATION":  102,
	"DANCE":          201,
	"HIP_HOP":        202,
	"ZUMBA":          203,
}

func (x FitnessCategory) String() string {
	return proto.EnumName(FitnessCategory_name, int32(x))
}
func (FitnessCategory) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EventType int32

const (
	EventType_LOGIN_EVENT       EventType = 0
	EventType_LOGOUT_EVENT      EventType = 1
	EventType_DEVICE_USED       EventType = 2
	EventType_JOIN_SESSION      EventType = 101
	EventType_FOLLOW_INSTRUCTOR EventType = 102
	EventType_LIKE_PRESS_WATCH  EventType = 201
)

var EventType_name = map[int32]string{
	0:   "LOGIN_EVENT",
	1:   "LOGOUT_EVENT",
	2:   "DEVICE_USED",
	101: "JOIN_SESSION",
	102: "FOLLOW_INSTRUCTOR",
	201: "LIKE_PRESS_WATCH",
}
var EventType_value = map[string]int32{
	"LOGIN_EVENT":       0,
	"LOGOUT_EVENT":      1,
	"DEVICE_USED":       2,
	"JOIN_SESSION":      101,
	"FOLLOW_INSTRUCTOR": 102,
	"LIKE_PRESS_WATCH":  201,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ServerSvcStatusReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ServerSvcStatusReq) Reset()                    { *m = ServerSvcStatusReq{} }
func (m *ServerSvcStatusReq) String() string            { return proto.CompactTextString(m) }
func (*ServerSvcStatusReq) ProtoMessage()               {}
func (*ServerSvcStatusReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerSvcStatusReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ServerSvcStatusReply struct {
	// ErrorData errData = 1;
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ServerSvcStatusReply) Reset()                    { *m = ServerSvcStatusReply{} }
func (m *ServerSvcStatusReply) String() string            { return proto.CompactTextString(m) }
func (*ServerSvcStatusReply) ProtoMessage()               {}
func (*ServerSvcStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerSvcStatusReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SessionInfo struct {
	// Timestamp sessionTime = 1;
	SessionTime  string            `protobuf:"bytes,1,opt,name=sessionTime" json:"sessionTime,omitempty"`
	SessionDesc  string            `protobuf:"bytes,2,opt,name=sessionDesc" json:"sessionDesc,omitempty"`
	InstructorID string            `protobuf:"bytes,3,opt,name=instructorID" json:"instructorID,omitempty"`
	SessionType  []FitnessCategory `protobuf:"varint,4,rep,packed,name=sessionType,enum=serversvc.FitnessCategory" json:"sessionType,omitempty"`
	// Maintained by server
	SessionUsersEnrolled uint64 `protobuf:"varint,5,opt,name=sessionUsersEnrolled" json:"sessionUsersEnrolled,omitempty"`
}

func (m *SessionInfo) Reset()                    { *m = SessionInfo{} }
func (m *SessionInfo) String() string            { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()               {}
func (*SessionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SessionInfo) GetSessionTime() string {
	if m != nil {
		return m.SessionTime
	}
	return ""
}

func (m *SessionInfo) GetSessionDesc() string {
	if m != nil {
		return m.SessionDesc
	}
	return ""
}

func (m *SessionInfo) GetInstructorID() string {
	if m != nil {
		return m.InstructorID
	}
	return ""
}

func (m *SessionInfo) GetSessionType() []FitnessCategory {
	if m != nil {
		return m.SessionType
	}
	return nil
}

func (m *SessionInfo) GetSessionUsersEnrolled() uint64 {
	if m != nil {
		return m.SessionUsersEnrolled
	}
	return 0
}

type ReviewInfo struct {
	ReviewList []*ReviewInfo_Review `protobuf:"bytes,1,rep,name=reviewList" json:"reviewList,omitempty"`
}

func (m *ReviewInfo) Reset()                    { *m = ReviewInfo{} }
func (m *ReviewInfo) String() string            { return proto.CompactTextString(m) }
func (*ReviewInfo) ProtoMessage()               {}
func (*ReviewInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReviewInfo) GetReviewList() []*ReviewInfo_Review {
	if m != nil {
		return m.ReviewList
	}
	return nil
}

type ReviewInfo_Review struct {
	Rating float32 `protobuf:"fixed32,1,opt,name=rating" json:"rating,omitempty"`
	Review string  `protobuf:"bytes,2,opt,name=review" json:"review,omitempty"`
}

func (m *ReviewInfo_Review) Reset()                    { *m = ReviewInfo_Review{} }
func (m *ReviewInfo_Review) String() string            { return proto.CompactTextString(m) }
func (*ReviewInfo_Review) ProtoMessage()               {}
func (*ReviewInfo_Review) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *ReviewInfo_Review) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *ReviewInfo_Review) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

type CCInfo struct {
	CcList []*CCInfo_CreditCard `protobuf:"bytes,1,rep,name=ccList" json:"ccList,omitempty"`
}

func (m *CCInfo) Reset()                    { *m = CCInfo{} }
func (m *CCInfo) String() string            { return proto.CompactTextString(m) }
func (*CCInfo) ProtoMessage()               {}
func (*CCInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CCInfo) GetCcList() []*CCInfo_CreditCard {
	if m != nil {
		return m.CcList
	}
	return nil
}

type CCInfo_CreditCard struct {
	Name        string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Number      string `protobuf:"bytes,2,opt,name=Number,json=number" json:"Number,omitempty"`
	ExpiryMonth string `protobuf:"bytes,3,opt,name=ExpiryMonth,json=expiryMonth" json:"ExpiryMonth,omitempty"`
	ExpiryYear  string `protobuf:"bytes,4,opt,name=ExpiryYear,json=expiryYear" json:"ExpiryYear,omitempty"`
	CCV         string `protobuf:"bytes,5,opt,name=CCV,json=cCV" json:"CCV,omitempty"`
	IsDefault   bool   `protobuf:"varint,6,opt,name=isDefault" json:"isDefault,omitempty"`
}

func (m *CCInfo_CreditCard) Reset()                    { *m = CCInfo_CreditCard{} }
func (m *CCInfo_CreditCard) String() string            { return proto.CompactTextString(m) }
func (*CCInfo_CreditCard) ProtoMessage()               {}
func (*CCInfo_CreditCard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *CCInfo_CreditCard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CCInfo_CreditCard) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *CCInfo_CreditCard) GetExpiryMonth() string {
	if m != nil {
		return m.ExpiryMonth
	}
	return ""
}

func (m *CCInfo_CreditCard) GetExpiryYear() string {
	if m != nil {
		return m.ExpiryYear
	}
	return ""
}

func (m *CCInfo_CreditCard) GetCCV() string {
	if m != nil {
		return m.CCV
	}
	return ""
}

func (m *CCInfo_CreditCard) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

type BankInfo struct {
	RoutingNum string `protobuf:"bytes,1,opt,name=RoutingNum,json=routingNum" json:"RoutingNum,omitempty"`
	AcctNum    string `protobuf:"bytes,2,opt,name=AcctNum,json=acctNum" json:"AcctNum,omitempty"`
	BankName   string `protobuf:"bytes,3,opt,name=BankName,json=bankName" json:"BankName,omitempty"`
}

func (m *BankInfo) Reset()                    { *m = BankInfo{} }
func (m *BankInfo) String() string            { return proto.CompactTextString(m) }
func (*BankInfo) ProtoMessage()               {}
func (*BankInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BankInfo) GetRoutingNum() string {
	if m != nil {
		return m.RoutingNum
	}
	return ""
}

func (m *BankInfo) GetAcctNum() string {
	if m != nil {
		return m.AcctNum
	}
	return ""
}

func (m *BankInfo) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

type InstructorInfo struct {
	FirstName          string            `protobuf:"bytes,1,opt,name=firstName" json:"firstName,omitempty"`
	Age                string            `protobuf:"bytes,2,opt,name=age" json:"age,omitempty"`
	Sex                string            `protobuf:"bytes,3,opt,name=sex" json:"sex,omitempty"`
	Location           string            `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	Email              string            `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	UserName           string            `protobuf:"bytes,6,opt,name=userName" json:"userName,omitempty"`
	PassWord           string            `protobuf:"bytes,7,opt,name=passWord" json:"passWord,omitempty"`
	Desc               string            `protobuf:"bytes,8,opt,name=desc" json:"desc,omitempty"`
	Certification      string            `protobuf:"bytes,9,opt,name=certification" json:"certification,omitempty"`
	FitnessSpecialties []FitnessCategory `protobuf:"varint,10,rep,packed,name=fitnessSpecialties,enum=serversvc.FitnessCategory" json:"fitnessSpecialties,omitempty"`
	LastName           string            `protobuf:"bytes,11,opt,name=lastName" json:"lastName,omitempty"`
	City               string            `protobuf:"bytes,12,opt,name=city" json:"city,omitempty"`
	Country            string            `protobuf:"bytes,13,opt,name=country" json:"country,omitempty"`
	// Internal to server
	ReviewInfoID string `protobuf:"bytes,101,opt,name=ReviewInfoID,json=reviewInfoID" json:"ReviewInfoID,omitempty"`
	BankInfoID   string `protobuf:"bytes,102,opt,name=BankInfoID,json=bankInfoID" json:"BankInfoID,omitempty"`
}

func (m *InstructorInfo) Reset()                    { *m = InstructorInfo{} }
func (m *InstructorInfo) String() string            { return proto.CompactTextString(m) }
func (*InstructorInfo) ProtoMessage()               {}
func (*InstructorInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InstructorInfo) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *InstructorInfo) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *InstructorInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *InstructorInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *InstructorInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InstructorInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *InstructorInfo) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *InstructorInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *InstructorInfo) GetCertification() string {
	if m != nil {
		return m.Certification
	}
	return ""
}

func (m *InstructorInfo) GetFitnessSpecialties() []FitnessCategory {
	if m != nil {
		return m.FitnessSpecialties
	}
	return nil
}

func (m *InstructorInfo) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *InstructorInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *InstructorInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *InstructorInfo) GetReviewInfoID() string {
	if m != nil {
		return m.ReviewInfoID
	}
	return ""
}

func (m *InstructorInfo) GetBankInfoID() string {
	if m != nil {
		return m.BankInfoID
	}
	return ""
}

type Device struct {
	DeviceID   string `protobuf:"bytes,1,opt,name=DeviceID,json=deviceID" json:"DeviceID,omitempty"`
	DeviceDesc string `protobuf:"bytes,2,opt,name=DeviceDesc,json=deviceDesc" json:"DeviceDesc,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Device) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *Device) GetDeviceDesc() string {
	if m != nil {
		return m.DeviceDesc
	}
	return ""
}

type UserInfo struct {
	FirstName string `protobuf:"bytes,1,opt,name=firstName" json:"firstName,omitempty"`
	Age       string `protobuf:"bytes,2,opt,name=age" json:"age,omitempty"`
	Sex       string `protobuf:"bytes,3,opt,name=sex" json:"sex,omitempty"`
	City      string `protobuf:"bytes,4,opt,name=city" json:"city,omitempty"`
	Country   string `protobuf:"bytes,5,opt,name=country" json:"country,omitempty"`
	Email     string `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	UserName  string `protobuf:"bytes,7,opt,name=userName" json:"userName,omitempty"`
	PassWord  string `protobuf:"bytes,8,opt,name=passWord" json:"passWord,omitempty"`
	LastName  string `protobuf:"bytes,9,opt,name=lastName" json:"lastName,omitempty"`
	CCInfoID  string `protobuf:"bytes,50,opt,name=CCInfoID,json=cCInfoID" json:"CCInfoID,omitempty"`
	// Internal to server
	FriendsIDs []string `protobuf:"bytes,101,rep,name=friendsIDs" json:"friendsIDs,omitempty"`
	FollowIDs  []string `protobuf:"bytes,102,rep,name=followIDs" json:"followIDs,omitempty"`
	// Pointer to event activity in DB
	RecordActivityID string `protobuf:"bytes,103,opt,name=RecordActivityID,json=recordActivityID" json:"RecordActivityID,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserInfo) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserInfo) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *UserInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *UserInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UserInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *UserInfo) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserInfo) GetCCInfoID() string {
	if m != nil {
		return m.CCInfoID
	}
	return ""
}

func (m *UserInfo) GetFriendsIDs() []string {
	if m != nil {
		return m.FriendsIDs
	}
	return nil
}

func (m *UserInfo) GetFollowIDs() []string {
	if m != nil {
		return m.FollowIDs
	}
	return nil
}

func (m *UserInfo) GetRecordActivityID() string {
	if m != nil {
		return m.RecordActivityID
	}
	return ""
}

type GetSessionsReq struct {
	// If specified, only show sessions of this type.
	SessionType string `protobuf:"bytes,1,opt,name=sessionType" json:"sessionType,omitempty"`
}

func (m *GetSessionsReq) Reset()                    { *m = GetSessionsReq{} }
func (m *GetSessionsReq) String() string            { return proto.CompactTextString(m) }
func (*GetSessionsReq) ProtoMessage()               {}
func (*GetSessionsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetSessionsReq) GetSessionType() string {
	if m != nil {
		return m.SessionType
	}
	return ""
}

type GetSessionsReply struct {
	SessionList []*SessionInfo `protobuf:"bytes,2,rep,name=sessionList" json:"sessionList,omitempty"`
}

func (m *GetSessionsReply) Reset()                    { *m = GetSessionsReply{} }
func (m *GetSessionsReply) String() string            { return proto.CompactTextString(m) }
func (*GetSessionsReply) ProtoMessage()               {}
func (*GetSessionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetSessionsReply) GetSessionList() []*SessionInfo {
	if m != nil {
		return m.SessionList
	}
	return nil
}

type GetSessionReply struct {
	Info *SessionInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *GetSessionReply) Reset()                    { *m = GetSessionReply{} }
func (m *GetSessionReply) String() string            { return proto.CompactTextString(m) }
func (*GetSessionReply) ProtoMessage()               {}
func (*GetSessionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetSessionReply) GetInfo() *SessionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetSessionReq struct {
	SessionKey string `protobuf:"bytes,1,opt,name=sessionKey" json:"sessionKey,omitempty"`
}

func (m *GetSessionReq) Reset()                    { *m = GetSessionReq{} }
func (m *GetSessionReq) String() string            { return proto.CompactTextString(m) }
func (*GetSessionReq) ProtoMessage()               {}
func (*GetSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetSessionReq) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

type PostSessionReq struct {
	Info *SessionInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *PostSessionReq) Reset()                    { *m = PostSessionReq{} }
func (m *PostSessionReq) String() string            { return proto.CompactTextString(m) }
func (*PostSessionReq) ProtoMessage()               {}
func (*PostSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PostSessionReq) GetInfo() *SessionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type PostSessionReply struct {
	SessionKey string `protobuf:"bytes,1,opt,name=sessionKey" json:"sessionKey,omitempty"`
}

func (m *PostSessionReply) Reset()                    { *m = PostSessionReply{} }
func (m *PostSessionReply) String() string            { return proto.CompactTextString(m) }
func (*PostSessionReply) ProtoMessage()               {}
func (*PostSessionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PostSessionReply) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

type EnrollInstructorReq struct {
	Instructor *InstructorInfo `protobuf:"bytes,1,opt,name=instructor" json:"instructor,omitempty"`
}

func (m *EnrollInstructorReq) Reset()                    { *m = EnrollInstructorReq{} }
func (m *EnrollInstructorReq) String() string            { return proto.CompactTextString(m) }
func (*EnrollInstructorReq) ProtoMessage()               {}
func (*EnrollInstructorReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *EnrollInstructorReq) GetInstructor() *InstructorInfo {
	if m != nil {
		return m.Instructor
	}
	return nil
}

type EnrollInstructorReply struct {
	InstructorKey string `protobuf:"bytes,1,opt,name=instructorKey" json:"instructorKey,omitempty"`
}

func (m *EnrollInstructorReply) Reset()                    { *m = EnrollInstructorReply{} }
func (m *EnrollInstructorReply) String() string            { return proto.CompactTextString(m) }
func (*EnrollInstructorReply) ProtoMessage()               {}
func (*EnrollInstructorReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *EnrollInstructorReply) GetInstructorKey() string {
	if m != nil {
		return m.InstructorKey
	}
	return ""
}

type GetInstructorReq struct {
	InstructorKey string `protobuf:"bytes,1,opt,name=instructorKey" json:"instructorKey,omitempty"`
}

func (m *GetInstructorReq) Reset()                    { *m = GetInstructorReq{} }
func (m *GetInstructorReq) String() string            { return proto.CompactTextString(m) }
func (*GetInstructorReq) ProtoMessage()               {}
func (*GetInstructorReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetInstructorReq) GetInstructorKey() string {
	if m != nil {
		return m.InstructorKey
	}
	return ""
}

type GetInstructorReply struct {
	Info *InstructorInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *GetInstructorReply) Reset()                    { *m = GetInstructorReply{} }
func (m *GetInstructorReply) String() string            { return proto.CompactTextString(m) }
func (*GetInstructorReply) ProtoMessage()               {}
func (*GetInstructorReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetInstructorReply) GetInfo() *InstructorInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetInstructorsReq struct {
	// If specified, only show sessions of this type.
	SessionType string `protobuf:"bytes,1,opt,name=sessionType" json:"sessionType,omitempty"`
}

func (m *GetInstructorsReq) Reset()                    { *m = GetInstructorsReq{} }
func (m *GetInstructorsReq) String() string            { return proto.CompactTextString(m) }
func (*GetInstructorsReq) ProtoMessage()               {}
func (*GetInstructorsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetInstructorsReq) GetSessionType() string {
	if m != nil {
		return m.SessionType
	}
	return ""
}

type GetInstructorsReply struct {
}

func (m *GetInstructorsReply) Reset()                    { *m = GetInstructorsReply{} }
func (m *GetInstructorsReply) String() string            { return proto.CompactTextString(m) }
func (*GetInstructorsReply) ProtoMessage()               {}
func (*GetInstructorsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type GetUserReq struct {
	UserKey string `protobuf:"bytes,1,opt,name=userKey" json:"userKey,omitempty"`
}

func (m *GetUserReq) Reset()                    { *m = GetUserReq{} }
func (m *GetUserReq) String() string            { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()               {}
func (*GetUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetUserReq) GetUserKey() string {
	if m != nil {
		return m.UserKey
	}
	return ""
}

type GetUserReply struct {
	Info *UserInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *GetUserReply) Reset()                    { *m = GetUserReply{} }
func (m *GetUserReply) String() string            { return proto.CompactTextString(m) }
func (*GetUserReply) ProtoMessage()               {}
func (*GetUserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetUserReply) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type EnrollUserReq struct {
	User *UserInfo `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *EnrollUserReq) Reset()                    { *m = EnrollUserReq{} }
func (m *EnrollUserReq) String() string            { return proto.CompactTextString(m) }
func (*EnrollUserReq) ProtoMessage()               {}
func (*EnrollUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *EnrollUserReq) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type EnrollUserReply struct {
	UserKey string `protobuf:"bytes,1,opt,name=userKey" json:"userKey,omitempty"`
}

func (m *EnrollUserReply) Reset()                    { *m = EnrollUserReply{} }
func (m *EnrollUserReply) String() string            { return proto.CompactTextString(m) }
func (*EnrollUserReply) ProtoMessage()               {}
func (*EnrollUserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *EnrollUserReply) GetUserKey() string {
	if m != nil {
		return m.UserKey
	}
	return ""
}

type GetUsersReq struct {
}

func (m *GetUsersReq) Reset()                    { *m = GetUsersReq{} }
func (m *GetUsersReq) String() string            { return proto.CompactTextString(m) }
func (*GetUsersReq) ProtoMessage()               {}
func (*GetUsersReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type GetUsersReply struct {
	UserList []*UserInfo `protobuf:"bytes,1,rep,name=userList" json:"userList,omitempty"`
}

func (m *GetUsersReply) Reset()                    { *m = GetUsersReply{} }
func (m *GetUsersReply) String() string            { return proto.CompactTextString(m) }
func (*GetUsersReply) ProtoMessage()               {}
func (*GetUsersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GetUsersReply) GetUserList() []*UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

type Event struct {
	EventType EventType `protobuf:"varint,1,opt,name=eventType,enum=serversvc.EventType" json:"eventType,omitempty"`
	// Duration eventDuration = 2;
	// google.protobuf.Timestamp eventTS = 3;
	EventDesc string `protobuf:"bytes,4,opt,name=eventDesc" json:"eventDesc,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Event) GetEventType() EventType {
	if m != nil {
		return m.EventType
	}
	return EventType_LOGIN_EVENT
}

func (m *Event) GetEventDesc() string {
	if m != nil {
		return m.EventDesc
	}
	return ""
}

type RecordActivity struct {
	EventList []*Event `protobuf:"bytes,1,rep,name=eventList" json:"eventList,omitempty"`
}

func (m *RecordActivity) Reset()                    { *m = RecordActivity{} }
func (m *RecordActivity) String() string            { return proto.CompactTextString(m) }
func (*RecordActivity) ProtoMessage()               {}
func (*RecordActivity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *RecordActivity) GetEventList() []*Event {
	if m != nil {
		return m.EventList
	}
	return nil
}

type RecordEventReq struct {
	Event *Event `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
}

func (m *RecordEventReq) Reset()                    { *m = RecordEventReq{} }
func (m *RecordEventReq) String() string            { return proto.CompactTextString(m) }
func (*RecordEventReq) ProtoMessage()               {}
func (*RecordEventReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *RecordEventReq) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type RecordEventReply struct {
}

func (m *RecordEventReply) Reset()                    { *m = RecordEventReply{} }
func (m *RecordEventReply) String() string            { return proto.CompactTextString(m) }
func (*RecordEventReply) ProtoMessage()               {}
func (*RecordEventReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type LoginReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	PassWord string `protobuf:"bytes,3,opt,name=passWord" json:"passWord,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *LoginReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginReq) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

type LoginReply struct {
	UserOrInstructorID string `protobuf:"bytes,2,opt,name=userOrInstructorID" json:"userOrInstructorID,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *LoginReply) GetUserOrInstructorID() string {
	if m != nil {
		return m.UserOrInstructorID
	}
	return ""
}

func init() {
	proto.RegisterType((*ServerSvcStatusReq)(nil), "serversvc.ServerSvcStatusReq")
	proto.RegisterType((*ServerSvcStatusReply)(nil), "serversvc.ServerSvcStatusReply")
	proto.RegisterType((*SessionInfo)(nil), "serversvc.SessionInfo")
	proto.RegisterType((*ReviewInfo)(nil), "serversvc.ReviewInfo")
	proto.RegisterType((*ReviewInfo_Review)(nil), "serversvc.ReviewInfo.Review")
	proto.RegisterType((*CCInfo)(nil), "serversvc.CCInfo")
	proto.RegisterType((*CCInfo_CreditCard)(nil), "serversvc.CCInfo.CreditCard")
	proto.RegisterType((*BankInfo)(nil), "serversvc.BankInfo")
	proto.RegisterType((*InstructorInfo)(nil), "serversvc.InstructorInfo")
	proto.RegisterType((*Device)(nil), "serversvc.Device")
	proto.RegisterType((*UserInfo)(nil), "serversvc.UserInfo")
	proto.RegisterType((*GetSessionsReq)(nil), "serversvc.GetSessionsReq")
	proto.RegisterType((*GetSessionsReply)(nil), "serversvc.GetSessionsReply")
	proto.RegisterType((*GetSessionReply)(nil), "serversvc.GetSessionReply")
	proto.RegisterType((*GetSessionReq)(nil), "serversvc.GetSessionReq")
	proto.RegisterType((*PostSessionReq)(nil), "serversvc.PostSessionReq")
	proto.RegisterType((*PostSessionReply)(nil), "serversvc.PostSessionReply")
	proto.RegisterType((*EnrollInstructorReq)(nil), "serversvc.EnrollInstructorReq")
	proto.RegisterType((*EnrollInstructorReply)(nil), "serversvc.EnrollInstructorReply")
	proto.RegisterType((*GetInstructorReq)(nil), "serversvc.GetInstructorReq")
	proto.RegisterType((*GetInstructorReply)(nil), "serversvc.GetInstructorReply")
	proto.RegisterType((*GetInstructorsReq)(nil), "serversvc.GetInstructorsReq")
	proto.RegisterType((*GetInstructorsReply)(nil), "serversvc.GetInstructorsReply")
	proto.RegisterType((*GetUserReq)(nil), "serversvc.GetUserReq")
	proto.RegisterType((*GetUserReply)(nil), "serversvc.GetUserReply")
	proto.RegisterType((*EnrollUserReq)(nil), "serversvc.EnrollUserReq")
	proto.RegisterType((*EnrollUserReply)(nil), "serversvc.EnrollUserReply")
	proto.RegisterType((*GetUsersReq)(nil), "serversvc.GetUsersReq")
	proto.RegisterType((*GetUsersReply)(nil), "serversvc.GetUsersReply")
	proto.RegisterType((*Event)(nil), "serversvc.Event")
	proto.RegisterType((*RecordActivity)(nil), "serversvc.RecordActivity")
	proto.RegisterType((*RecordEventReq)(nil), "serversvc.RecordEventReq")
	proto.RegisterType((*RecordEventReply)(nil), "serversvc.RecordEventReply")
	proto.RegisterType((*LoginReq)(nil), "serversvc.LoginReq")
	proto.RegisterType((*LoginReply)(nil), "serversvc.LoginReply")
	proto.RegisterEnum("serversvc.FitnessCategory", FitnessCategory_name, FitnessCategory_value)
	proto.RegisterEnum("serversvc.EventType", EventType_name, EventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ServerSvc service

type ServerSvcClient interface {
	// Is it running?
	// DONE
	GetStatus(ctx context.Context, in *ServerSvcStatusReq, opts ...grpc.CallOption) (*ServerSvcStatusReply, error)
	// Session handling
	GetSessions(ctx context.Context, in *GetSessionsReq, opts ...grpc.CallOption) (*GetSessionsReply, error)
	// DONE
	PostSession(ctx context.Context, in *PostSessionReq, opts ...grpc.CallOption) (*PostSessionReply, error)
	// DONE
	GetSession(ctx context.Context, in *GetSessionReq, opts ...grpc.CallOption) (*GetSessionReply, error)
	// Instructor handling
	EnrollInstructor(ctx context.Context, in *EnrollInstructorReq, opts ...grpc.CallOption) (*EnrollInstructorReply, error)
	GetInstructor(ctx context.Context, in *GetInstructorReq, opts ...grpc.CallOption) (*GetInstructorReply, error)
	GetInstructors(ctx context.Context, in *GetInstructorsReq, opts ...grpc.CallOption) (*GetInstructorsReply, error)
	// User handling
	EnrollUser(ctx context.Context, in *EnrollUserReq, opts ...grpc.CallOption) (*EnrollUserReply, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserReply, error)
	GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersReply, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error)
	// Used for analytics
	// Client will record much of the user interaction with the app
	RecordEvent(ctx context.Context, in *RecordEventReq, opts ...grpc.CallOption) (*RecordEventReply, error)
}

type serverSvcClient struct {
	cc *grpc.ClientConn
}

func NewServerSvcClient(cc *grpc.ClientConn) ServerSvcClient {
	return &serverSvcClient{cc}
}

func (c *serverSvcClient) GetStatus(ctx context.Context, in *ServerSvcStatusReq, opts ...grpc.CallOption) (*ServerSvcStatusReply, error) {
	out := new(ServerSvcStatusReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) GetSessions(ctx context.Context, in *GetSessionsReq, opts ...grpc.CallOption) (*GetSessionsReply, error) {
	out := new(GetSessionsReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/GetSessions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) PostSession(ctx context.Context, in *PostSessionReq, opts ...grpc.CallOption) (*PostSessionReply, error) {
	out := new(PostSessionReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/PostSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) GetSession(ctx context.Context, in *GetSessionReq, opts ...grpc.CallOption) (*GetSessionReply, error) {
	out := new(GetSessionReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/GetSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) EnrollInstructor(ctx context.Context, in *EnrollInstructorReq, opts ...grpc.CallOption) (*EnrollInstructorReply, error) {
	out := new(EnrollInstructorReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/EnrollInstructor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) GetInstructor(ctx context.Context, in *GetInstructorReq, opts ...grpc.CallOption) (*GetInstructorReply, error) {
	out := new(GetInstructorReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/GetInstructor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) GetInstructors(ctx context.Context, in *GetInstructorsReq, opts ...grpc.CallOption) (*GetInstructorsReply, error) {
	out := new(GetInstructorsReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/GetInstructors", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) EnrollUser(ctx context.Context, in *EnrollUserReq, opts ...grpc.CallOption) (*EnrollUserReply, error) {
	out := new(EnrollUserReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/EnrollUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserReply, error) {
	out := new(GetUserReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) GetUsers(ctx context.Context, in *GetUsersReq, opts ...grpc.CallOption) (*GetUsersReply, error) {
	out := new(GetUsersReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverSvcClient) RecordEvent(ctx context.Context, in *RecordEventReq, opts ...grpc.CallOption) (*RecordEventReply, error) {
	out := new(RecordEventReply)
	err := grpc.Invoke(ctx, "/serversvc.ServerSvc/RecordEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServerSvc service

type ServerSvcServer interface {
	// Is it running?
	// DONE
	GetStatus(context.Context, *ServerSvcStatusReq) (*ServerSvcStatusReply, error)
	// Session handling
	GetSessions(context.Context, *GetSessionsReq) (*GetSessionsReply, error)
	// DONE
	PostSession(context.Context, *PostSessionReq) (*PostSessionReply, error)
	// DONE
	GetSession(context.Context, *GetSessionReq) (*GetSessionReply, error)
	// Instructor handling
	EnrollInstructor(context.Context, *EnrollInstructorReq) (*EnrollInstructorReply, error)
	GetInstructor(context.Context, *GetInstructorReq) (*GetInstructorReply, error)
	GetInstructors(context.Context, *GetInstructorsReq) (*GetInstructorsReply, error)
	// User handling
	EnrollUser(context.Context, *EnrollUserReq) (*EnrollUserReply, error)
	GetUser(context.Context, *GetUserReq) (*GetUserReply, error)
	GetUsers(context.Context, *GetUsersReq) (*GetUsersReply, error)
	Login(context.Context, *LoginReq) (*LoginReply, error)
	// Used for analytics
	// Client will record much of the user interaction with the app
	RecordEvent(context.Context, *RecordEventReq) (*RecordEventReply, error)
}

func RegisterServerSvcServer(s *grpc.Server, srv ServerSvcServer) {
	s.RegisterService(&_ServerSvc_serviceDesc, srv)
}

func _ServerSvc_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerSvcStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).GetStatus(ctx, req.(*ServerSvcStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/GetSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).GetSessions(ctx, req.(*GetSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_PostSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).PostSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/PostSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).PostSession(ctx, req.(*PostSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).GetSession(ctx, req.(*GetSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_EnrollInstructor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollInstructorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).EnrollInstructor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/EnrollInstructor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).EnrollInstructor(ctx, req.(*EnrollInstructorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_GetInstructor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstructorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).GetInstructor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/GetInstructor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).GetInstructor(ctx, req.(*GetInstructorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_GetInstructors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstructorsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).GetInstructors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/GetInstructors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).GetInstructors(ctx, req.(*GetInstructorsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_EnrollUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).EnrollUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/EnrollUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).EnrollUser(ctx, req.(*EnrollUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).GetUsers(ctx, req.(*GetUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerSvc_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerSvcServer).RecordEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serversvc.ServerSvc/RecordEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerSvcServer).RecordEvent(ctx, req.(*RecordEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serversvc.ServerSvc",
	HandlerType: (*ServerSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ServerSvc_GetStatus_Handler,
		},
		{
			MethodName: "GetSessions",
			Handler:    _ServerSvc_GetSessions_Handler,
		},
		{
			MethodName: "PostSession",
			Handler:    _ServerSvc_PostSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _ServerSvc_GetSession_Handler,
		},
		{
			MethodName: "EnrollInstructor",
			Handler:    _ServerSvc_EnrollInstructor_Handler,
		},
		{
			MethodName: "GetInstructor",
			Handler:    _ServerSvc_GetInstructor_Handler,
		},
		{
			MethodName: "GetInstructors",
			Handler:    _ServerSvc_GetInstructors_Handler,
		},
		{
			MethodName: "EnrollUser",
			Handler:    _ServerSvc_EnrollUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _ServerSvc_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _ServerSvc_GetUsers_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ServerSvc_Login_Handler,
		},
		{
			MethodName: "RecordEvent",
			Handler:    _ServerSvc_RecordEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serverrpc.proto",
}

func init() { proto.RegisterFile("serverrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x72, 0xdb, 0xc4,
	0x17, 0xaf, 0xe3, 0xc4, 0xb1, 0x4f, 0x12, 0x47, 0xdd, 0x26, 0xfd, 0xfb, 0x6f, 0xda, 0x92, 0xd1,
	0x30, 0x25, 0x13, 0x86, 0x94, 0x31, 0x74, 0x08, 0x43, 0x61, 0x70, 0x65, 0x37, 0x51, 0xeb, 0xd8,
	0x19, 0xd9, 0x49, 0x29, 0x37, 0x46, 0x91, 0xd7, 0x41, 0x43, 0x22, 0xb9, 0x92, 0x9c, 0xd6, 0x57,
	0xdc, 0xf0, 0x0e, 0xbc, 0x03, 0x6f, 0x02, 0xdc, 0xf0, 0x16, 0xcc, 0xc0, 0x0c, 0xcf, 0xc0, 0x7e,
	0x49, 0xda, 0x95, 0x3f, 0x5a, 0x66, 0xb8, 0xdb, 0xf3, 0x3b, 0x9f, 0x7b, 0xf6, 0xec, 0x6f, 0x65,
	0xc3, 0x66, 0x88, 0x83, 0x6b, 0x1c, 0x04, 0x23, 0x67, 0x7f, 0x14, 0xf8, 0x91, 0x8f, 0x4a, 0x1c,
	0x08, 0xaf, 0x1d, 0x7d, 0x17, 0x50, 0x97, 0x09, 0xdd, 0x6b, 0xa7, 0x1b, 0xd9, 0xd1, 0x38, 0xb4,
	0xf0, 0x4b, 0x84, 0x60, 0xd9, 0xb3, 0xaf, 0x70, 0x25, 0xb7, 0x93, 0xdb, 0x2d, 0x59, 0x6c, 0xad,
	0x7f, 0x04, 0x5b, 0x53, 0x96, 0xa3, 0xcb, 0x09, 0xaa, 0xc0, 0xea, 0x15, 0x0e, 0x43, 0xfb, 0x22,
	0x36, 0x8f, 0x45, 0xfd, 0x8f, 0x1c, 0xac, 0x75, 0xc9, 0xda, 0xf5, 0x3d, 0xd3, 0x1b, 0xfa, 0x68,
	0x07, 0xd6, 0x42, 0x2e, 0xf6, 0xdc, 0x24, 0xb8, 0x0c, 0x49, 0x16, 0x0d, 0x1c, 0x3a, 0x95, 0x25,
	0xc5, 0x82, 0x42, 0x48, 0x87, 0x75, 0xd7, 0x0b, 0xa3, 0x60, 0xec, 0x44, 0x7e, 0x60, 0x36, 0x2a,
	0x79, 0x66, 0xa2, 0x60, 0xe8, 0x51, 0x9a, 0x67, 0x32, 0xc2, 0x95, 0xe5, 0x9d, 0xfc, 0x6e, 0xb9,
	0x56, 0xdd, 0x4f, 0x36, 0xbd, 0xff, 0xc4, 0x8d, 0x3c, 0x62, 0x60, 0xd8, 0x11, 0xbe, 0xf0, 0x83,
	0x89, 0x25, 0x9b, 0xa3, 0x1a, 0x6c, 0x09, 0xf1, 0x94, 0x78, 0x84, 0x4d, 0x2f, 0xf0, 0x2f, 0x2f,
	0xf1, 0xa0, 0xb2, 0x42, 0x32, 0x2d, 0x5b, 0x33, 0x75, 0xfa, 0x8f, 0x39, 0x00, 0x0b, 0x5f, 0xbb,
	0xf8, 0x15, 0xdb, 0xe8, 0x23, 0x80, 0x80, 0x49, 0x2d, 0x37, 0x8c, 0xc8, 0x3e, 0xf3, 0xbb, 0x6b,
	0xb5, 0x3b, 0x52, 0xfe, 0xd4, 0x54, 0x2c, 0x2d, 0xc9, 0xbe, 0x7a, 0x00, 0x05, 0x8e, 0xa2, 0xdb,
	0x50, 0x08, 0xec, 0xc8, 0xf5, 0x2e, 0x58, 0xaf, 0x96, 0x2c, 0x21, 0x31, 0x9c, 0x59, 0x88, 0x0e,
	0x09, 0x49, 0xff, 0x2b, 0x07, 0x05, 0xc3, 0x60, 0x25, 0x7c, 0x02, 0x05, 0xc7, 0x99, 0x93, 0x9e,
	0x9b, 0xec, 0x1b, 0x01, 0x1e, 0xb8, 0x91, 0x61, 0x07, 0x03, 0x4b, 0xd8, 0x56, 0x7f, 0x26, 0xfb,
	0x48, 0x61, 0x3a, 0x06, 0xed, 0xcc, 0x18, 0xd0, 0xdc, 0xed, 0xf1, 0xd5, 0x39, 0x0e, 0xe2, 0xdc,
	0x1e, 0x93, 0xe8, 0xd1, 0x35, 0x5f, 0x8f, 0xdc, 0x60, 0x72, 0xec, 0x7b, 0xd1, 0x77, 0xe2, 0x5c,
	0xd6, 0x70, 0x0a, 0xa1, 0x7b, 0x00, 0xdc, 0xe2, 0x05, 0xb6, 0x03, 0x72, 0x2a, 0xd4, 0x00, 0x70,
	0x82, 0x20, 0x0d, 0xf2, 0x86, 0x71, 0xc6, 0xfa, 0x5c, 0xb2, 0xf2, 0x8e, 0x71, 0x86, 0xee, 0x40,
	0xc9, 0x0d, 0x1b, 0x78, 0x68, 0x8f, 0x2f, 0xa3, 0x4a, 0x81, 0xe0, 0x45, 0x2b, 0x05, 0xf4, 0x6f,
	0xa1, 0xf8, 0xd8, 0xf6, 0xbe, 0x67, 0xdb, 0x25, 0xb1, 0x2d, 0x7f, 0x4c, 0x9b, 0x43, 0x8a, 0x13,
	0xf5, 0x42, 0x90, 0x20, 0x74, 0x48, 0xeb, 0x8e, 0x13, 0x51, 0x25, 0x2f, 0x7b, 0xd5, 0xe6, 0x22,
	0xaa, 0xf2, 0x28, 0x6c, 0x9f, 0xbc, 0xe8, 0xe2, 0xb9, 0x90, 0xf5, 0xdf, 0xf3, 0x50, 0x36, 0xd3,
	0xc9, 0xa2, 0x89, 0x48, 0x49, 0x43, 0x37, 0x08, 0x23, 0xa9, 0x2f, 0x29, 0x40, 0xb7, 0x40, 0xef,
	0x01, 0x4f, 0x41, 0x97, 0x14, 0x09, 0xf1, 0x6b, 0x11, 0x99, 0x2e, 0x69, 0xc2, 0x4b, 0xdf, 0x21,
	0x07, 0xe9, 0x7b, 0xa2, 0x09, 0x89, 0x8c, 0xb6, 0x60, 0x05, 0x5f, 0xd9, 0xee, 0xa5, 0x68, 0x02,
	0x17, 0xa8, 0xc7, 0x98, 0x9c, 0x1e, 0x4b, 0x59, 0xe0, 0x1e, 0xb1, 0x4c, 0x75, 0x23, 0x3b, 0x0c,
	0x9f, 0xfb, 0xc1, 0xa0, 0xb2, 0xca, 0x75, 0xb1, 0x4c, 0x8f, 0x6f, 0x40, 0xaf, 0x51, 0x91, 0x1f,
	0x1f, 0x5d, 0xa3, 0xf7, 0x60, 0xc3, 0xc1, 0x41, 0xe4, 0x0e, 0x5d, 0x51, 0x42, 0x89, 0x29, 0x55,
	0x10, 0x3d, 0x05, 0x34, 0xe4, 0x77, 0xa4, 0x3b, 0xc2, 0x8e, 0x6b, 0x5f, 0x46, 0x2e, 0x0e, 0x2b,
	0xf0, 0xc6, 0x8b, 0x34, 0xc3, 0x8b, 0xed, 0xd7, 0x16, 0x0d, 0x5b, 0x13, 0xfb, 0x15, 0x32, 0xad,
	0xd0, 0x71, 0xa3, 0x49, 0x65, 0x9d, 0x57, 0x48, 0xd7, 0xf4, 0xa8, 0x1c, 0x7f, 0xec, 0x45, 0xc1,
	0xa4, 0xb2, 0xc1, 0x8f, 0x4a, 0x88, 0xf4, 0xee, 0xa7, 0x37, 0x87, 0xdc, 0x7d, 0xcc, 0xef, 0x7e,
	0x20, 0x61, 0x74, 0x10, 0xe2, 0xa1, 0x20, 0x16, 0x43, 0x3e, 0x08, 0xe7, 0x09, 0xa2, 0x37, 0xa0,
	0xd0, 0x20, 0xf6, 0x0e, 0xeb, 0x1c, 0x5f, 0x11, 0x3b, 0x7e, 0x90, 0xc5, 0x81, 0x90, 0x69, 0x14,
	0xae, 0x93, 0x68, 0x08, 0x06, 0x09, 0xa2, 0xff, 0xb9, 0x04, 0x45, 0xca, 0x00, 0xff, 0xd1, 0x48,
	0xc4, 0x6d, 0x58, 0x9e, 0xdd, 0x86, 0x15, 0xb5, 0x0d, 0xc9, 0x90, 0x14, 0xe6, 0x0d, 0xc9, 0xea,
	0x82, 0x21, 0x29, 0x66, 0x86, 0x44, 0x3e, 0x9e, 0x52, 0xe6, 0x78, 0x88, 0x8e, 0x73, 0x05, 0x69,
	0x51, 0x8d, 0xeb, 0x1c, 0x23, 0x6d, 0xf4, 0x30, 0x70, 0xb1, 0x37, 0x08, 0xcd, 0x46, 0x48, 0x8e,
	0x22, 0x4f, 0x5b, 0x94, 0x22, 0xac, 0x2b, 0x84, 0x1c, 0xfd, 0x57, 0x54, 0x3d, 0x64, 0xea, 0x14,
	0x40, 0x7b, 0xa0, 0x59, 0xd8, 0x21, 0xf9, 0xeb, 0x4e, 0xe4, 0x5e, 0x93, 0xfd, 0x92, 0x0c, 0x17,
	0x2c, 0x83, 0x16, 0x64, 0x70, 0xbd, 0x06, 0xe5, 0x43, 0x1c, 0x89, 0x87, 0x84, 0x3d, 0x4f, 0x3b,
	0x2a, 0xc1, 0x67, 0x1e, 0x12, 0x02, 0xe9, 0x2d, 0xd0, 0x14, 0x1f, 0xfa, 0x50, 0x1d, 0x24, 0x5e,
	0x8c, 0x17, 0x97, 0x18, 0x2f, 0xde, 0x96, 0xa6, 0x59, 0x7a, 0xab, 0x2c, 0xd9, 0x54, 0xff, 0x02,
	0x36, 0xd3, 0x68, 0x3c, 0xd8, 0x1e, 0x2c, 0xbb, 0xc4, 0x8e, 0xe5, 0x9e, 0x1f, 0x85, 0xd9, 0xe8,
	0x0f, 0x60, 0x43, 0x76, 0x7f, 0x49, 0x7b, 0x27, 0xc2, 0x3f, 0xc3, 0x93, 0x98, 0xad, 0x52, 0x44,
	0x7f, 0x04, 0xe5, 0x13, 0x3f, 0x94, 0x3d, 0xfe, 0x4d, 0xba, 0x1a, 0x68, 0x8a, 0x37, 0x2d, 0xf7,
	0x4d, 0x19, 0x4f, 0xe0, 0x16, 0x7f, 0xcc, 0x52, 0xba, 0xa3, 0x69, 0x3f, 0x03, 0x48, 0x5f, 0x56,
	0x91, 0xfc, 0xff, 0x52, 0x72, 0x95, 0x1c, 0x2d, 0xc9, 0x98, 0xf4, 0x6c, 0x7b, 0x3a, 0x22, 0x2d,
	0x85, 0x30, 0x50, 0x6a, 0x96, 0x56, 0xa3, 0x82, 0xfa, 0x01, 0x3b, 0x40, 0xb5, 0x9a, 0xb7, 0xf3,
	0x34, 0x00, 0x65, 0x3c, 0x69, 0xd6, 0x0f, 0x95, 0x06, 0x2e, 0xd8, 0x03, 0xef, 0xe1, 0x43, 0xb8,
	0xa9, 0x04, 0x79, 0xcb, 0xb1, 0xdb, 0x86, 0x5b, 0x59, 0x37, 0x92, 0x5c, 0xbf, 0x0f, 0x40, 0x60,
	0x4a, 0x18, 0x34, 0x0c, 0xb9, 0xd9, 0xf4, 0x66, 0xa6, 0x1b, 0x88, 0x45, 0xfd, 0x53, 0x58, 0x4f,
	0xec, 0x68, 0xd1, 0xef, 0x2b, 0x45, 0xdf, 0x92, 0x8a, 0x8e, 0xc9, 0x47, 0x94, 0x7b, 0x00, 0x1b,
	0xbc, 0xd9, 0x71, 0x0e, 0xe2, 0x49, 0x83, 0x2e, 0xf4, 0xa4, 0x06, 0xfa, 0x07, 0xb0, 0x29, 0x7b,
	0x8a, 0x0f, 0xba, 0x39, 0xf5, 0x6d, 0xc0, 0x9a, 0xa8, 0x8f, 0xf6, 0x43, 0xff, 0x8a, 0xcd, 0xb5,
	0x10, 0xa9, 0xe7, 0x03, 0xce, 0x41, 0xd2, 0x67, 0xc7, 0xcc, 0xcc, 0x89, 0x91, 0xfe, 0x02, 0x56,
	0x9a, 0xd7, 0xd8, 0x8b, 0xc8, 0x47, 0x57, 0x09, 0xd3, 0x45, 0xd2, 0xd8, 0x72, 0x6d, 0x4b, 0x72,
	0x6d, 0xc6, 0x3a, 0x2b, 0x35, 0xa3, 0x0c, 0xc3, 0x04, 0xc6, 0xd1, 0x9c, 0x3a, 0x53, 0x80, 0x14,
	0x57, 0x56, 0x19, 0x06, 0xed, 0x0b, 0x7b, 0xa9, 0x3c, 0x2d, 0x9b, 0xc3, 0x4a, 0x4d, 0x48, 0x53,
	0x45, 0x04, 0xae, 0x21, 0x5d, 0xbd, 0x4f, 0x98, 0x97, 0xae, 0x45, 0x5b, 0xa7, 0xbd, 0xb9, 0x5a,
	0x47, 0x31, 0xbb, 0x09, 0x4f, 0x3a, 0x03, 0x5f, 0x43, 0xb1, 0xe5, 0x5f, 0xb8, 0xec, 0x36, 0x27,
	0x0c, 0x9e, 0x9b, 0xc7, 0xe0, 0x4b, 0x0b, 0x18, 0x3c, 0xaf, 0x32, 0x38, 0x61, 0x0b, 0x10, 0x91,
	0xe9, 0x19, 0xec, 0x03, 0xa2, 0x5e, 0x9d, 0xc0, 0x94, 0x3f, 0x93, 0x79, 0xbc, 0x19, 0x9a, 0xbd,
	0x9f, 0x72, 0xb0, 0x99, 0x79, 0xc6, 0x51, 0x11, 0x96, 0x5f, 0x74, 0x0e, 0xeb, 0xda, 0x0d, 0x54,
	0x06, 0x38, 0xaa, 0xf7, 0x8e, 0xea, 0x7d, 0x26, 0xe7, 0xc8, 0x4b, 0x55, 0x7e, 0x76, 0xda, 0x6e,
	0xd4, 0x5b, 0x66, 0xdb, 0xe4, 0xd8, 0x12, 0xda, 0x80, 0xd2, 0x93, 0x7a, 0xb7, 0xc7, 0xc5, 0x3c,
	0x75, 0x39, 0x6e, 0x36, 0xcc, 0x5e, 0xbd, 0x67, 0x76, 0xda, 0x1a, 0x46, 0x37, 0x61, 0xa3, 0x77,
	0xdc, 0x97, 0xa0, 0x21, 0x02, 0x58, 0x69, 0xd4, 0xdb, 0x46, 0x53, 0xfb, 0x25, 0x87, 0xd6, 0x61,
	0xf5, 0xc8, 0x3c, 0xe9, 0x1f, 0x75, 0x4e, 0xb4, 0x5f, 0x73, 0x54, 0xf3, 0xcd, 0xe9, 0xf1, 0xe3,
	0xba, 0xf6, 0x5b, 0x6e, 0xef, 0x07, 0x28, 0x25, 0xe7, 0x8e, 0x36, 0x61, 0xad, 0xd5, 0x39, 0x34,
	0xdb, 0xfd, 0xe6, 0x59, 0xb3, 0xdd, 0x23, 0x95, 0x69, 0xb0, 0x4e, 0x80, 0xce, 0x69, 0x4f, 0x20,
	0x39, 0x6a, 0xd2, 0x68, 0x9e, 0x99, 0x46, 0xb3, 0x7f, 0xda, 0x6d, 0x36, 0x48, 0x61, 0xc4, 0xe4,
	0x69, 0x87, 0xb8, 0x74, 0x9b, 0xdd, 0x2e, 0xaf, 0x65, 0x1b, 0x6e, 0x3e, 0xe9, 0xb4, 0x5a, 0x9d,
	0xe7, 0x7d, 0xb3, 0xdd, 0xed, 0x59, 0xa7, 0x46, 0xaf, 0x63, 0x91, 0x7a, 0xb6, 0x41, 0x6b, 0x99,
	0xcf, 0x9a, 0xfd, 0x13, 0x8b, 0x58, 0xf6, 0x9f, 0xd7, 0x7b, 0xc6, 0x11, 0x29, 0xad, 0xf6, 0x77,
	0x01, 0x4a, 0xc9, 0x4f, 0x1e, 0x74, 0x0c, 0x25, 0xca, 0xe2, 0xec, 0x97, 0x0f, 0xba, 0xab, 0x30,
	0x70, 0xf6, 0xf7, 0x53, 0xf5, 0xdd, 0x45, 0x6a, 0x3a, 0x0d, 0x37, 0xd0, 0x21, 0xbb, 0x4b, 0xf1,
	0x0b, 0x85, 0x64, 0x46, 0x52, 0x5f, 0xbb, 0xea, 0x3b, 0xf3, 0x54, 0x49, 0x20, 0x89, 0xee, 0x95,
	0x40, 0xea, 0x23, 0xa2, 0x04, 0xca, 0xbe, 0x10, 0x24, 0x50, 0x83, 0xb1, 0x54, 0x1c, 0xa7, 0x32,
	0x33, 0x2b, 0x0d, 0x53, 0x9d, 0xa3, 0xe1, 0x51, 0xce, 0x40, 0xcb, 0xf2, 0x3e, 0xba, 0x27, 0x5f,
	0x94, 0xe9, 0x67, 0xa6, 0xba, 0xb3, 0x50, 0xcf, 0xe3, 0x1e, 0x33, 0xb2, 0x91, 0x82, 0x66, 0xda,
	0xa2, 0x46, 0xbc, 0x3b, 0x5f, 0xc9, 0xc3, 0x9d, 0xb0, 0x8f, 0x0a, 0x89, 0xa9, 0xd1, 0x9d, 0x79,
	0x2e, 0xec, 0x10, 0xee, 0x2d, 0xd0, 0x26, 0xed, 0x4b, 0x99, 0x54, 0x69, 0x9f, 0x42, 0xcd, 0x4a,
	0xfb, 0x32, 0xd4, 0x4b, 0xa2, 0x7c, 0x0e, 0xab, 0x82, 0x53, 0xd1, 0xb6, 0x9a, 0x32, 0xf6, 0xff,
	0xdf, 0x2c, 0x98, 0x3b, 0x7f, 0x09, 0xc5, 0x98, 0x90, 0xd1, 0xed, 0x69, 0x33, 0xb6, 0x91, 0xca,
	0x4c, 0x9c, 0xfb, 0x3f, 0x84, 0x15, 0xc6, 0x24, 0x48, 0xa6, 0xed, 0x98, 0xb5, 0xaa, 0xdb, 0xd3,
	0x60, 0x32, 0x81, 0x12, 0xdd, 0x29, 0x13, 0xa8, 0x12, 0xa8, 0x32, 0x81, 0x53, 0x0c, 0x79, 0xe3,
	0xbc, 0xc0, 0xfe, 0x9e, 0xf8, 0xf8, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0x73, 0x1b, 0xbe,
	0xb1, 0x10, 0x00, 0x00,
}
